extends: ../optimizers.yaml
name: TileModel
params:
  encoder:
    name: ViTEncoder
    params:
      model_name: "hf_hub:prov-gigapath/prov-gigapath"
      pretrained: true
  decoders:
    tissue_segmentation:
      name: DPTDecoder
      params:
        output_channels: 22
        embed_dim: 1536
        feature_channels: 256
        head_channels: 128
        patch_size: 16
        num_prefix_tokens: 1
        dropout: 0.25
        upsample_mode: bilinear
        align_corners: true
  task_weights:
    tissue_segmentation: 3.0
  task_kwargs:
    tissue_segmentation:
      unknown_class_index: 0
