params:
  decoders:
    magnification:
      name: Classifier
      params:
        hidden_dims: [512, 256, 128]
        output_dim: 4
        preproc: maxpool
        dropout: 0.2
  task_weights:
    magnification: 1.0
