params:
  decoders:
    hematoxylin:
      name: UNetDecoder
      params:
        output_channels: 1
        encoder_channels: [64, 256, 512, 1024, 2048]
        decoder_channels: [512, 256, 128, 64]
        dropout: 0.25
        upsample_mode: bilinear
        align_corners: true
  task_weights:
    hematoxylin: 1.0
