name: TCGATileDataset
params:
  magnification_mpps: [0.25, 0.5, 1.0, 2.0]
  jigmag_mpps: [0.25, 0.5, 1.0, 2.0]
  tiles_per_slide: 64
  train_budget: 0.4
  val_budget: 0.2
  test_budget: 0.4
  batch_size: 16
  train_fraction: 0.70
  val_fraction: 0.15
  test_fraction: 0.15
