extends: common-params.yaml
name: DualCLAM
params:
  enc_dim: 2048
  main_task: subtyping
  pretext_tasks: null
  hidden_dims: [256, 128]
  output_dims:
    subtyping: 8
  dropout: 0.2
  attn_kwargs:
    multi_branch: true
    gated: false
    hidden_dim: 256
    dropout: 0.25
  cluster_kwargs:
    k_sample: 8
    inst_weight: 0.25
    out_of_class: true
checkpoint_path: checkpoints/clam-mb-resnet50-none.pth
