params:
  optimizer:
    name: adamw
    params:
      lr: 1e-4
      weight_decay: 1e-2
  lr_scheduler:
    name: cosineannealinglr
    params:
      T_max: 10
      eta_min: 1e-6
  task_weights:
    tissue_segmentation: 3.0
    magnification: 1.0
    hematoxylin: 1.0
    jigmag: 1.0
    sbs_regression: 1.0
    subtyping: 2.0
  task_kwargs:
    tissue_segmentation:
      unknown_class_index: 0
    subtyping:
      unknown_class_index: 0
