name: TCGAFeatureDataset
params:
  root_dir: data/TCGA-BRCA-test
  features_dir: data/TCGA-BRCA-test/features/resnet50-full
  main_task: subtyping
  pretext_tasks:
    - sbs_regression
  portion_per_sample: 0.25
  train_fraction: 0.7
  val_fraction: 0.15
  test_fraction: 0.15
  random_seed: 42
  batch_size: 8
  num_workers: 2
  expected_encoder_name: ResNetEncoder
