extends: common-params.yaml
params:
  encoder_config: encoder-resnet50.yaml
  decoders_config:
    tissue_segmentation: decoder-unet50-tissue-segmentation.yaml
    hematoxylin: decoder-unet50-hematoxylin.yaml
checkpoint_path: checkpoints/resnet50-hematoxylin.pth
