extends: common-params.yaml
params:
  encoder_config: encoder-prov-gigapath.yaml
  decoders_config:
    tissue_segmentation: decoder-dpt-tissue-segmentation.yaml
    magnification: decoder-classifier-identity-magnification.yaml
    hematoxylin: decoder-dpt-hematoxylin.yaml
    jigmag: decoder-classifier-identity-jigmag.yaml
checkpoint_path: checkpoints/prov-gigapath-full.pth
