extends: common-params.yaml
params:
  encoder_config: encoder-prov-gigapath.yaml
  decoders_config:
    tissue_segmentation: decoder-dpt-tissue-segmentation.yaml
    hematoxylin: decoder-dpt-hematoxylin.yaml
checkpoint_path: checkpoints/prov-gigapath-hematoxylin.pth
